# Generated by Django 4.2 on 2023-05-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("telefone", models.CharField(max_length=20)),
                ("data", models.DateField()),
                ("hora", models.TimeField()),
                ("observacao", models.TextField(blank=True)),
            ],
        ),
    ]
