# Generated by Django 4.2 on 2023-05-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_contato_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="data",
            field=models.DateField(auto_now_add=True),
        ),
    ]
