# Generated by Django 4.2 on 2023-05-10 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_reserva_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contato",
            old_name="observacao",
            new_name="mensagem",
        ),
    ]
