# Generated by Django 4.2 on 2023-05-10 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_observacao_contato_mensagem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reserva",
            old_name="hora",
            new_name="horario",
        ),
    ]
