# Generated by Django 4.2 on 2023-05-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_reserva_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="data",
            field=models.DateTimeField(),
        ),
    ]
